[services-ng] put mysql tmp dir on /var/vcap/data
Change-Id: If398a021c71822cb188dbcfa78347229c78a590a

diff --git a/jobs/mysql_node_ng/templates/warden_ctl b/jobs/mysql_node_ng/templates/warden_ctl
--- a/jobs/mysql_node_ng/templates/warden_ctl
+++ b/jobs/mysql_node_ng/templates/warden_ctl
@@ -41,6 +41,13 @@ case $1 in
     rm -rf $ROOT_DIR/$MYSQL55_DIR/initdb55
     rsync -arl $MYSQL55_DIR/initdb55 $ROOT_DIR/$MYSQL55_DIR
 
+    /var/vcap/jobs/mysql_node_ng/bin/create_mysql_tmp_dir
+    return_value=$?
+    if [ $return_value -ne 0 ]; then
+      echo "Failed to create mysql tmp directory"
+      exit $return_value
+    fi
+
     echo "Starting warden."
 
     start_warden
