Have UAA use new route-registrar job.
* UAA has a template to write out route-registrar url
* route-registrar job looks for a file named route_registrar_port_map_config
* cf-registrar only does varz information and no longer speaks to nats

[#99063270]

Signed-off-by: Dan Lavine <dlavine@us.ibm.com>

diff --git a/jobs/route_registrar/templates/route_registrar_ctl.erb b/jobs/route_registrar/templates/route_registrar_ctl.erb
--- a/jobs/route_registrar/templates/route_registrar_ctl.erb
+++ b/jobs/route_registrar/templates/route_registrar_ctl.erb
@@ -11,6 +11,15 @@ source /var/vcap/packages/common/utils.sh
 case $1 in
 
   start)
+    route_registrar_port_map=$(find -L /var/vcap/jobs/ -name route_registrar_port_map)
+
+    if [ -e $route_registrar_port_map ]; then
+      echo "route registration port map location $route_registrar_port_map"
+    else
+      echo "Could not find route registration"
+      exit 1
+    fi
+
     pid_guard $PIDFILE "route_registrar"
 
     mkdir -p $RUN_DIR
@@ -22,7 +31,7 @@ case $1 in
     echo $$ > $PIDFILE
 
     cd /var/vcap/packages/route_registrar/route_registrar
-    exec chpst -u vcap:vcap /var/vcap/packages/ruby-2.1.7/bin/bundle exec ./bin/route-registrar /var/vcap/jobs/route_registrar/config/config.yml
+    exec chpst -u vcap:vcap /var/vcap/packages/ruby-2.1.7/bin/bundle exec ./bin/route-registrar /var/vcap/jobs/route_registrar/config/config.yml $route_registrar_port_map
 
     ;;
 
