use ccng db:migrate and bump ccng
git shortlog 868793da31..ae1291560

Brad Midgley (2):
  upgrade uaa, add admin scope test for upgraded uaa
  Merge "upgrade uaa, add admin scope test for upgraded uaa"

Patrick Bozeman (1):
    db:migrate for ccng

Change-Id: Ic6d458432a146d563d7faef5d27f3556c67a9528

diff --git a/jobs/cloud_controller_ng/templates/cloud_controller_ng_ctl.erb b/jobs/cloud_controller_ng/templates/cloud_controller_ng_ctl.erb
--- a/jobs/cloud_controller_ng/templates/cloud_controller_ng_ctl.erb
+++ b/jobs/cloud_controller_ng/templates/cloud_controller_ng_ctl.erb
@@ -106,6 +106,16 @@ case $1 in
 
     # Run the migrations only on the first CC launch
     <% if spec.index.to_i == 0 %>
+      cd $CC_PACKAGE_DIR/cloud_controller_ng
+      chpst -u vcap:vcap bundle exec rake db:migrate >>$LOG_DIR/db_migrate.stdout.log 2>>$LOG_DIR/db_migrate.stderr.log
+      if [ $? != 0 ]; then
+        echo "Migrations failed"
+        exit 1
+      fi
+
+      # TODO: remove the -m when we have a stand alone utility for loading
+      # frameworks etc, and call those utilities here.  See corresponding
+      # comments in ccng runner.
       exec chpst -u vcap:vcap $CC_PACKAGE_DIR/cloud_controller_ng/bin/cloud_controller -m \
         -c $CLOUD_CONTROLLER_NG_CONFIG \
         >>$LOG_DIR/cloud_controller_ng.stdout.log \
