Check if mounting failed at startup script
Change-Id: I8634197ddb276571ede4778d12197f9f88cececf

diff --git a/jobs/backup_manager/templates/backup_manager_ctl.erb b/jobs/backup_manager/templates/backup_manager_ctl.erb
--- a/jobs/backup_manager/templates/backup_manager_ctl.erb
+++ b/jobs/backup_manager/templates/backup_manager_ctl.erb
@@ -36,7 +36,7 @@ case $1 in
     if [ ! -d $MOUNT_POINT ]; then
       mkdir -p $MOUNT_POINT
     fi
-    mount -t nfs <%= nfs_server.address %>:<%= nfs_server.export_dir %> $MOUNT_POINT
+    mount -t nfs <%= nfs_server.address %>:<%= nfs_server.export_dir %> $MOUNT_POINT || (echo "Fail to mount $MOUNT_POINT"; exit 1)
     <% end %>
 
     exec /var/vcap/packages/backup_manager/bin/services/backup_manager \
