Check that consul is sync'd
[#98998108]

Signed-off-by: Andrew Edgar <aedgar@ca.ibm.com>

diff --git a/jobs/consul_agent/templates/agent_ctl.sh.erb b/jobs/consul_agent/templates/agent_ctl.sh.erb
--- a/jobs/consul_agent/templates/agent_ctl.sh.erb
+++ b/jobs/consul_agent/templates/agent_ctl.sh.erb
@@ -8,12 +8,20 @@ CONF_DIR=/var/vcap/jobs/consul_agent/config
 
 PKG=/var/vcap/packages/consul
 
+PID_FILE=$RUN_DIR/consul_agent.pid
+NODE_NAME='<%="#{name.gsub('_', '-')}-#{spec.index}"%>'
+
+source /var/vcap/packages/common/utils.sh
+
 mkdir -p /var/vcap/sys/log/monit
 exec 1>> /var/vcap/sys/log/monit/consul_agent.out.log
 exec 2>> /var/vcap/sys/log/monit/consul_agent.err.log
 
 case $1 in
   start)
+
+    pid_guard ${PIDFILE} "consul_agent"
+
     mkdir -p $LOG_DIR
     chown -R vcap:vcap $LOG_DIR
 
@@ -75,11 +83,39 @@ EOF
 
     export GOMAXPROCS
 
-    exec chpst -u vcap:vcap $PKG/bin/consul agent \
-      -pid-file=${RUN_DIR}/consul_agent.pid \
+    chpst -u vcap:vcap $PKG/bin/consul agent \
       -config-dir=$CONF_DIR \
       2> >(tee -a ${LOG_DIR}/consul_agent.stderr.log | logger -p user.error -t vcap.consul-agent) \
-      1> >(tee -a ${LOG_DIR}/consul_agent.stdout.log | logger -p user.info  -t vcap.consul-agent)
+      1> >(tee -a ${LOG_DIR}/consul_agent.stdout.log | logger -p user.info  -t vcap.consul-agent) &
+
+    consul_pid=$!
+
+    echo "Consul pid is " + $consul_pid
+
+    server=<%=p("consul.agent.mode") == "server"%>
+    if [ "$server" == "true" ]; then
+      synched=false
+
+      for i in $(seq <%= p("consul.agent.sync_timeout_in_seconds") %>); do
+        if curl -s 'http://127.0.0.1:8500/v1/health/service/consul' | grep -oP "\{\"Node\":\"$NODE_NAME\".*?}]" | grep '"Tags":\[\]'; then
+          synched=true
+          break
+        fi
+        sleep 1
+      done
+
+      if ${synced}; then
+        echo "$(date) Consul is synced"
+      else
+        echo "$(date) Consul failed to sync"
+        $PKG/bin/consul leave
+        kill -9 ${consul_pid}
+        exit 1
+      fi
+    fi
+
+    echo ${consul_pid} > $PID_FILE
+    wait ${consul_pid}
 
     ;;
 
