Enable consul security and tweak agent start script
[finishes #100841008]

Signed-off-by: Connor Braa <cbraa@pivotal.io>

diff --git a/jobs/consul_agent/templates/agent_ctl.sh.erb b/jobs/consul_agent/templates/agent_ctl.sh.erb
--- a/jobs/consul_agent/templates/agent_ctl.sh.erb
+++ b/jobs/consul_agent/templates/agent_ctl.sh.erb
@@ -18,6 +18,16 @@ mkdir -p /var/vcap/sys/log/monit
 exec 1>> /var/vcap/sys/log/monit/consul_agent.out.log
 exec 2>> /var/vcap/sys/log/monit/consul_agent.err.log
 
+stop_consul() {
+  echo "$(date) Consul failed to start"
+  consul_pid=$1
+  if ! $PKG/bin/consul leave; then
+    kill ${consul_pid} || true
+  fi
+
+  wait ${consul_pid}
+}
+
 case $1 in
   start)
 
@@ -83,9 +93,6 @@ EOF
     expected=<%=p("consul.agent.servers.lan").size%>
     consul_join="<%=p("consul.agent.servers.lan").join(' ')%>"
     server=<%=p("consul.agent.mode") == "server"%>
-    if [ "$server" == "true" ]; then
-      actual=$(/var/vcap/packages/consul/bin/consul members -status=alive | grep server | wc -l)
-    fi
 
     setcap cap_net_bind_service=+ep $PKG/bin/consul
 
@@ -96,6 +103,10 @@ EOF
 
     export GOMAXPROCS
 
+    if [ "$server" != "true" ]; then
+      rm -f $DATA_DIR/serf/local.keyring
+    fi
+
     chpst -u vcap:vcap $PKG/bin/consul agent \
       -config-dir=$CONF_DIR \
       2> >(tee -a ${LOG_DIR}/consul_agent.stderr.log | logger -p user.error -t vcap.consul-agent) \
@@ -103,11 +114,14 @@ EOF
 
     consul_pid=$!
 
+    trap "stop_consul $consul_pid" ERR
+
     echo "Consul pid is " + $consul_pid
 
     start=0
-    synced=false
+    synced=true
     if [ $expected -gt 0 ]; then
+      synced=false
       consul_server_ips="<%=p("consul.agent.servers.lan").join('\\|')%>"
       for i in $(seq <%= p("consul.agent.sync_timeout_in_seconds") %>); do
         echo "$(date)" "Waiting to have joined one of: ${consul_join}"
@@ -121,26 +135,55 @@ EOF
       done
     fi
 
-    if [[ "$server" == "true" && $actual -eq $((expected - 1)) ]]; then
-      synced=false
-      for i in $(seq $start <%= p("consul.agent.sync_timeout_in_seconds") %>); do
-        if curl -s 'http://127.0.0.1:8500/v1/health/service/consul' | grep -oP "\{\"Node\":\"$NODE_NAME\".*?}]" | grep '"Tags":\[\]'; then
-          synced=true
-          break
+    if [ "$server" == "true" ]; then
+      actual=$($PKG/bin/consul members -status=alive | grep server | wc -l)
+
+      # only the last member of the cluster waits for leader election
+      if [[ $actual -eq $expected ]]; then
+        synced=false
+        for i in $(seq $start <%= p("consul.agent.sync_timeout_in_seconds") %>); do
+          info=$($PKG/bin/consul info)
+          commit_index=$(echo $info | grep -o "commit_index = [0-9]\+" | cut -d "=" -f2 | tr -d " ")
+          last_log_index=$(echo $info | grep -o "last_log_index = [0-9]\+" | cut -d "=" -f2 | tr -d " ")
+          echo "commit_index: $commit_index"
+          echo "last_log_index: $last_log_index"
+          if [[ $commit_index -ne 0 && $last_log_index -eq $commit_index ]]; then
+            synced=true
+            break
+          fi
+          sleep 1
+        done
+
+        leader=$(curl -s http://127.0.0.1:8500/v1/status/leader)
+
+        if [ "$leader" == '""' ]; then
+          echo "$(date) No leader found"
+          synced=false
         fi
-        sleep 1
-      done
+      fi
     fi
 
     if ${synced}; then
       echo "$(date) Consul is synced"
+
+      <% if p("consul.require_ssl") %>
+        <% if !p("consul.encrypt_keys").nil? && !p("consul.encrypt_keys").empty? %>
+          if [ "$server" == "true" ]; then
+            allkeys=$($PKG/bin/consul keyring -list | grep -oP '[^\s]{24}' | sort -u | awk '{ print $1 }')
+            extrakeys=$(echo $allkeys | xargs -n1 | grep -v '<%= p("consul.encrypt_keys").join('\\|') %>' | cat)
+            <% p("consul.encrypt_keys").each do |encrypt_key| %>
+              $PKG/bin/consul keyring -install='<%= encrypt_key %>'
+            <% end %>
+            $PKG/bin/consul keyring -use='<%= p("consul.encrypt_keys").first %>'
+            for toremove in $extrakeys ; do
+              $PKG/bin/consul keyring -remove="$toremove"
+            done
+          fi
+        <% end %>
+      <% end %>
     else
       echo "$(date) Consul failed to sync"
-      if ! $PKG/bin/consul leave; then
-        kill ${consul_pid} || true
-      fi
-
-      wait ${consul_pid}
+      stop_consul $consul_pid
       exit 1
     fi
 
