[services-ng]create loopback device for mongodb snapshot tmp_dir
Change-Id: Idbe38e48a9fecaaebd0be822d00c3663e9121b71

diff --git a/jobs/mongodb_node_ng/templates/mongodb_node_ctl b/jobs/mongodb_node_ng/templates/mongodb_node_ctl
--- a/jobs/mongodb_node_ng/templates/mongodb_node_ctl
+++ b/jobs/mongodb_node_ng/templates/mongodb_node_ctl
@@ -48,6 +48,13 @@ case $1 in
     chmod +x $JOB_DIR/config/mongodb_backup
     $JOB_DIR/config/mongodb_backup start
 
+    /var/vcap/jobs/mongodb_node_ng/bin/create_mongodb_tmp_dir
+    return_value=$?
+    if [ $return_value -ne 0 ]; then
+      echo "Failed to create mongodb tmp directory"
+      exit $return_value
+    fi
+
     (crontab -l | sed /mongodb_logrotate/d; cat /var/vcap/jobs/mongodb_node_ng/config/mongodb_logrotate.cron) | sed /^$/d | crontab
 
     exec /var/vcap/packages/mongodb_node_ng/services/ng/mongodb/bin/mongodb_node \
@@ -61,6 +68,7 @@ case $1 in
     kill_and_wait $PIDFILE 400 0
 
     crontab -l | sed /mongodb_logrotate/d | crontab
+    /var/vcap/jobs/mongodb_node_ng/bin/remove_mongodb_tmp_dir
 
     chmod +x $JOB_DIR/config/mongodb_backup
     $JOB_DIR/config/mongodb_backup stop
