postgres startup.log in
Change-Id: I35275869e0d23cc7482636042fcfc8e3bdd8b78d

diff --git a/jobs/postgresql_node/templates/postgresql_ctl.erb b/jobs/postgresql_node/templates/postgresql_ctl.erb
--- a/jobs/postgresql_node/templates/postgresql_ctl.erb
+++ b/jobs/postgresql_node/templates/postgresql_ctl.erb
@@ -1,12 +1,22 @@
-#!/bin/bash
+#!/bin/bash -e
+<% db = properties.send(properties.db) %>
 
-PACKAGE_DIR=/var/vcap/packages/postgresql
-DATA_DIR=/var/vcap/store/postgresql
-RUN_DIR=/var/vcap/sys/run/postgresql
-PIDFILE=$RUN_DIR/postgresql.pid
-LOG_DIR=/var/vcap/sys/log/postgresql
+PACKAGE_DIR=/var/vcap/packages/postgres
+JOB_DIR=/var/vcap/jobs/postgres
 
-FIRST_TIME=0
+STORE_DIR=/var/vcap/store
+DATA_DIR=$STORE_DIR/postgres
+
+RUN_DIR=/var/vcap/sys/run/postgres
+LOG_DIR=/var/vcap/sys/log/postgres
+
+# external_pid_file in postgresql.conf takes care of
+# overwriting $PIDFILE with actual DB server pid
+PIDFILE=$RUN_DIR/postgres.pid
+
+HOST="<%= db.address %>"
+PORT="<%= db.port %>"
+LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH
 
 source /var/vcap/packages/common/utils.sh
 
@@ -14,81 +24,97 @@ case "$1" in
   start)
     pid_guard $PIDFILE "PostgreSQL"
 
+    # TODO: This script is responsible for both
+    # starting PostgreSQL and running some queries
+    # (create DBs, roles, applying grants). One problem
+    # that needs to be addressed in the future is that
+    # if some queries fail job is still considered running.
+    # Later we'll change it to use a more involved approach
+    # (i.e. script that brings DB to sync)
+
     mkdir -p $RUN_DIR
-    echo $$ > $PIDFILE # Satisfy Monit in case of slow start
+    chown vcap:vcap $RUN_DIR
 
-    sysctl -w 'kernel.shmmax=284934144'
+    echo $$ > $PIDFILE
+    chown vcap:vcap $PIDFILE
 
-    if [ ! -d $DATA_DIR -o ! -f $DATA_DIR/postgresql.conf ]; then
-      FIRST_TIME=1
-      mkdir -p $DATA_DIR
-      chown vcap:vcap $DATA_DIR
+    sysctl -w "kernel.shmmax=284934144"
 
-      su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH $PACKAGE_DIR/bin/initdb -E utf8 -D $DATA_DIR"
-
-      if [ $? != 0 ]; then
-        echo "ERROR: Unable to initialize PostgreSQL DB"
-        exit 1
-      fi
-
-      echo "host all all 0.0.0.0/0 md5" >> $DATA_DIR/pg_hba.conf
-
-      # set listening address if supplied
-      <% if properties.postgresql_server && properties.postgresql_server.listen_address %>
-        sed -i "s/#listen_addresses\( *\)=\( *\)'localhost'/listen_addresses\1=\2'<%= properties.postgresql_server.listen_address %>'/" $DATA_DIR/postgresql.conf
-      <% else %>
-        sed -i "s/#listen_addresses\( *\)=\( *\)'localhost'/listen_addresses\1=\2'*'/" $DATA_DIR/postgresql.conf
-      <% end %>
+    if [ ! -d $STORE_DIR ]; then
+      echo "ERROR: storage directory doesn't exist"
+      echo "Please add persistent disk to this job"
+      exit 1
     fi
 
-    # since postgresql service is alive
-    # log dir change should cover both clean deploy and upgrade push
     if [ ! -d $LOG_DIR ]; then
       mkdir -p $LOG_DIR
       chown vcap:vcap $LOG_DIR
     fi
-    sed -i "/log_directory/ {s/#log_directory/log_directory/;s/pg_log/\/var\/vcap\/sys\/log\/postgresql/}" $DATA_DIR/postgresql.conf
 
-    # pg global max connections
-    # this can be updated by re-deployment rather than the first initialization
-    <% if properties.postgresql_server && properties.postgresql_server.max_connections %>
-    sed -i "s/^max_connections =.*/max_connections = <%= properties.postgresql_server.max_connections %>/" $DATA_DIR/postgresql.conf
+    if [ ! -d $DATA_DIR -o ! -f $DATA_DIR/postgresql.conf ]; then
+      mkdir -p $DATA_DIR
+      chown vcap:vcap $DATA_DIR
+
+      # initdb creates data directories
+      su - vcap -c "$PACKAGE_DIR/bin/initdb -E utf8 -D $DATA_DIR"
+
+      mkdir -p $DATA_DIR/pg_log
+      chown vcap:vcap $DATA_DIR/pg_log
+    fi
+
+    cp $JOB_DIR/config/{postgresql,pg_hba}.conf $DATA_DIR
+    chown vcap:vcap $DATA_DIR/{postgresql,pg_hba}.conf
+
+    echo "Starting PostgreSQL: "
+    su - vcap -c "$PACKAGE_DIR/bin/pg_ctl -o \"-h $HOST -p $PORT\" \
+                  -w start -D $DATA_DIR -l \"$LOG_DIR/startup.log\""
+
+    echo "PostgreSQL started successfully"
+
+    echo "Creating roles..."
+    <% db.roles.each do |role| %>
+      echo "Trying to create role <%= role.name %>..."
+      set +e
+      # TODO remove unused roles automatically
+      # Default permissions are: nosuperuser nologin inherit nocreatedb.
+      # Will fail if role already exists, which is OK
+      $PACKAGE_DIR/bin/psql -U vcap -p $PORT -d postgres \
+                            -c "CREATE ROLE \"<%= role.name %>\""
+      set -e
+
+      echo "Setting password for role <%= role.name %>..."
+      $PACKAGE_DIR/bin/psql -U vcap -p $PORT -d postgres \
+                            -c "ALTER ROLE \"<%= role.name %>\" \
+                                WITH LOGIN PASSWORD '<%= role.password %>'"
     <% end %>
 
-    # stop psql from adding timestamps to its log file names
-    sed -i "/log_filename/ {s/#log_filename/log_filename/;s/postgresql-%Y-%m-%d_%H%M%S.log/postgresql.log/}" $DATA_DIR/postgresql.conf
+    echo "Creating databases..."
+    <% db.databases.each do |database| %>
+      echo "Trying to create database <%= database.name %>..."
+      set +e
+      su - vcap -c "$PACKAGE_DIR/bin/createdb \"<%= database.name %>\" -p $PORT"
+      set -e
 
-    echo "Starting PostgreSQL 9.0: "
-    su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH $PACKAGE_DIR/bin/pg_ctl -w start -D $DATA_DIR -l \"$LOG_DIR/startup.log\""
-
-    if [ $? == 0 ]; then
-      echo "PostgreSQL 9.0 started successfully"
-      head -n 1 $DATA_DIR/postmaster.pid > $PIDFILE
-      if [ $FIRST_TIME -eq 1 ]; then
-        # Setup contrib packages
-        for sqlf in citext.sql fuzzystrmatch.sql isn.sql ltree.sql pageinspect.sql pg_buffercache.sql pgcrypto.sql pg_freespacemap.sql sslinfo.sql tablefunc.sql uuid-ossp.sql
-        do
-          echo "Installing contrib package ${sqlf}"
-          ${PACKAGE_DIR}/bin/psql -U vcap -f ${PACKAGE_DIR}/share/${sqlf} -d postgres
-        done
-      fi
-    else
-      rm $PIDFILE
-      echo "The PostgreSQL server start seems to have some problems, please see logs for details."
-      exit 1
-    fi
+      <% if database.run_on_every_startup %>
+        <% database.run_on_every_startup.each do |query| %>
+          $PACKAGE_DIR/bin/psql -U vcap -p $PORT \
+                                -d "<%= database.name %>" \
+                                -c "<%= query %>"
+        <% end %>
+      <% end %>
+    <% end %>
 
     ;;
 
   stop)
-    echo "Stopping PostgreSQL 9.0: "
-    su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH $PACKAGE_DIR/bin/pg_ctl stop -m fast -w -D $DATA_DIR"
+    echo "Stopping PostgreSQL: "
+    su - vcap -c "$PACKAGE_DIR/bin/pg_ctl stop -m fast -w -D $DATA_DIR"
     wait_pidfile $PIDFILE
 
     ;;
 
   status)
-    su - vcap -c "LD_LIBRARY_PATH=$PACKAGE_DIR/lib:$LD_LIBRARY_PATH $PACKAGE_DIR/bin/pg_ctl status -D $DATA_DIR"
+    su - vcap -c "$PACKAGE_DIR/bin/pg_ctl status -D $DATA_DIR"
 
     ;;
 
