Upgrade the JVM used by the UAA to jdk1.6u35
This package includes tools that can be used to debug in the case
of an outage. It also includes several security and bug fixes.

[#fixes 37793793]

Change-Id: I9a3bd6c1d42080661cfedab712e0ebf72d7ee39f

diff --git a/packages/uaa/packaging b/packages/uaa/packaging
--- a/packages/uaa/packaging
+++ b/packages/uaa/packaging
@@ -2,6 +2,16 @@
 set -e
 
 cd ${BOSH_INSTALL_TARGET}
+tar zxvf ${BOSH_COMPILE_TARGET}/uaa/jdk1.6.0_35.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Cannot unpack JDK"
+  exit 1
+fi
+
+mv jdk1.6.0_35 jdk
+ln -s jdk/jre
+
+cd ${BOSH_INSTALL_TARGET}
 
 tar zxvf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-7.0.32.tar.gz
 if [[ $? != 0 ]] ; then
