"merge" master blobs, uaa job, and dashboard job
Change-Id: Ifa9a6f55ad6d9c9e3caa1be022dd72e52a8ce3ef

diff --git a/packages/uaa/packaging b/packages/uaa/packaging
--- a/packages/uaa/packaging
+++ b/packages/uaa/packaging
@@ -2,18 +2,30 @@
 set -e
 
 cd ${BOSH_INSTALL_TARGET}
+tar zxvf ${BOSH_COMPILE_TARGET}/uaa/jdk1.6.0_35.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Cannot unpack JDK"
+  exit 1
+fi
 
-tar zxvf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-7.0.27.tar.gz
+mv jdk1.6.0_35 jdk
+ln -s jdk/jre
+
+cd ${BOSH_INSTALL_TARGET}
+
+tar zxvf ${BOSH_COMPILE_TARGET}/uaa/apache-tomcat-7.0.32.tar.gz
 if [[ $? != 0 ]] ; then
   echo "Cannot unpack Tomcat"
   exit 1
 fi
 
-mv apache-tomcat-7.0.27 tomcat
+mv apache-tomcat-7.0.32 tomcat
 
 cd tomcat
 rm -rf webapps/*
-cp -a ${BOSH_COMPILE_TARGET}/uaa/cloudfoundry-identity-uaa-1.1.2.war webapps/ROOT.war
+cp -a ${BOSH_COMPILE_TARGET}/uaa/cloudfoundry-identity-uaa-1.2.5.war webapps/ROOT.war
+cp -a ${BOSH_COMPILE_TARGET}/uaa/cloudfoundry-identity-batch-1.0.1.war webapps/batch.war
+cp -a ${BOSH_COMPILE_TARGET}/uaa/cloudfoundry-identity-varz-1.0.2.war webapps/varz.war
 
 cd ${BOSH_INSTALL_TARGET}
 cp -a ${BOSH_COMPILE_TARGET}/tools/vcap_registrar vcap_registrar
