add versions support for mongodb
Change-Id: If635d6de7460ae9c532b62860917a02730d8b64f

diff --git a/packages/mongodb/packaging b/packages/mongodb/packaging
--- a/packages/mongodb/packaging
+++ b/packages/mongodb/packaging
@@ -1,29 +1,39 @@
 # abort script on any command that exit with a non zero value
 set -e
+declare -A versions
+# version mapping from full version to short version
+versions['1.8.5']='1.8'
 
-if [[ `uname -a` =~ "x86_64" ]] ; then
-  name="mongodb-linux-x86_64-1.8.5"
-  echo "Using 64-bit version"
-else
-  name="mongodb-linux-i686-1.8.5"
-  echo "Using 32-bit version"
-fi
+for version in ${!versions[@]}; do
+  echo "Package mongodb version:$version"
 
-archive=mongodb/$name.tgz
+  if [[ `uname -a` =~ "x86_64" ]] ; then
+    name="mongodb-linux-x86_64-$version"
+    echo "Using 64-bit version"
+  else
+    name="mongodb-linux-i686-$version"
+    echo "Using 32-bit version"
+  fi
 
-if [[ -f $archive ]] ; then
-  echo "Archive found"
-else
-  echo "Archive not found"
-  exit 1
-fi
+  archive=mongodb/$name.tgz
 
-echo "Extracting archive..."
-tar xzf $archive
+  if [[ -f $archive ]] ; then
+    echo "Archive: $archive found"
+  else
+    echo "Archive: $archive not found"
+    exit 1
+  fi
 
-if [[ $? != 0 ]] ; then
-  echo "Cannot unpack mongodb"
-  exit 1
-fi
+  echo "Extracting archive..."
+  tar xzf $archive
 
-cp -a $name/* ${BOSH_INSTALL_TARGET}
+  if [[ $? != 0 ]] ; then
+    echo "Cannot unpack mongodb: $archive"
+    exit 1
+  fi
+
+  short_version=${versions[$version]}
+  target=${BOSH_INSTALL_TARGET}/$short_version
+  mkdir $target
+  cp -a $name/* $target
+done
