Fixing review comments

diff --git a/scripts/generate-cf-diego-certs b/scripts/generate-cf-diego-certs
--- a/scripts/generate-cf-diego-certs
+++ b/scripts/generate-cf-diego-certs
@@ -2,24 +2,31 @@
 
 set -e
 
-scripts_folder="$(dirname "$0")"
+SCRIPTS_FOLDER="$(dirname "$0")"
 
 # Place keys and certificates here
-depot_path="cf-diego-certs"
-ca_name="cf-diego-ca"
-mkdir -p "${depot_path}"
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="cf-diego-certs"
+CA_NAME="cf-diego-ca"
 
-if [[ "$1" == "--recreate-ca" ]] || [[ -z "$1" && ! -f "$depot_path/$ca_name.crt" ]]; then
+function create_ca {
   # CA to distribute to diego and cloud_controller
-  "${scripts_folder}"/generate_ca_cert --common-name "cfdiegoCA" --depot-path ${depot_path} --output-file "$ca_name"
-elif [[ -z "$1" && -f "$depot_path/$ca_name.crt" ]]; then
+  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "cfdiegoCA" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$CA_NAME"
+}
+
+if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
+fi
+
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
+
+if [[ "$2" == "--recreate-ca" ]] || [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
+  create_ca
+elif [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
   echo -e "\e[1m\e[33m[INFO] Using existing cf-diego CA, recreating only client/server certificates\e[0m"
 fi
 
 # Server certificate for cloud controller to act as a TLS server
-cc_cn=cloud-controller-ng.service.cf.internal
-certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name $cc_cn
-certstrap --depot-path ${depot_path} sign $cc_cn --CA "$ca_name"
-mv -f ${depot_path}/$cc_cn.key ${depot_path}/cloud-controller.key
-mv -f ${depot_path}/$cc_cn.csr ${depot_path}/cloud-controller.csr
-mv -f ${depot_path}/$cc_cn.crt ${depot_path}/cloud-controller.crt
+CC_CN="cloud-controller-ng.service.cf.internal"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "$CC_CN" --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file cloud-controller
diff --git a/scripts/generate-consul-certs b/scripts/generate-consul-certs
--- a/scripts/generate-consul-certs
+++ b/scripts/generate-consul-certs
@@ -2,21 +2,32 @@
 
 set -e
 
-scripts_folder="$(dirname "$0")"
+SCRIPTS_FOLDER="$(dirname "$0")"
 
-# Place keys and certificates here
-depot_path="consul-certs"
-mkdir -p ${depot_path}
-ca_name="consul-ca"
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="consul-certs"
+CA_NAME="consul-ca"
 
-if [[ "$1" == "--recreate-ca" ]] || [[ -z "$1" && ! -f "$depot_path/$ca_name.crt" ]]; then
-  "${scripts_folder}"/generate_ca_cert --common-name "consulCA" --depot-path ${depot_path} --output-file "$ca_name"
-elif [[ -z "$1" && -f "$depot_path/$ca_name.crt" ]]; then
+function create_ca {
+  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "consulCA" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$CA_NAME"
+}
+
+if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
+fi
+
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
+
+if [[ "$2" == "--recreate-ca" ]] || [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
+  create_ca
+elif [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
   echo -e "\e[1m\e[33m[INFO] Using existing consul CA, recreating only client/server certificates\e[0m"
 fi
 
+CC_CN="server.dc1.cf.internal"
 # Server certificate to share across the consul cluster
-"${scripts_folder}"/generate_end_entity_certs --common-name server.dc1.cf.internal --ca-name "$ca_name" --depot-path ${depot_path} --output-file server
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "$CC_CN" --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file server
 
 # Agent certificate to distribute to jobs that access consul
-"${scripts_folder}"/generate_end_entity_certs --common-name 'consul agent' --ca-name "$ca_name" --depot-path ${depot_path} --output-file agent
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name 'consul agent' --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file agent
diff --git a/scripts/generate-etcd-certs b/scripts/generate-etcd-certs
--- a/scripts/generate-etcd-certs
+++ b/scripts/generate-etcd-certs
@@ -2,27 +2,48 @@
 
 set -e
 
-scripts_folder="$(dirname "$0")"
+SCRIPTS_FOLDER="$(dirname "$0")"
 
-# Place keys and certificates here
-depot_path="etcd-certs"
-mkdir -p ${depot_path}
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="etcd-certs"
+CA_NAME="etcd-ca"
+PEER_CA_NAME="peer-ca"
 
+function create_ca {
+  # CA to distribute to diego and cloud_controller
+  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "$1" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$2"
+}
 
-if [[ "$1" == "--recreate-ca" ]] || [[ -z "$1" && ! -f "$depot_path/etcd-ca.crt" ]]; then
-    # CA to distribute to etcd clients and servers
-    "${scripts_folder}"/generate_ca_cert --common-name "etcdCA" --depot-path "${depot_path}" --output-file etcd-ca
-    # CA to distribute across etcd peerss
-    "${scripts_folder}"/generate_ca_cert --common-name "peerCA" --depot-path "${depot_path}" --output-file peer-ca
-elif [[ -z "$1" && -f "$depot_path/etcd-ca.crt" ]]; then
-    echo -e "\e[1m\e[33m[INFO] Using existing etcd/peer CA, recreating only client/server certificates\e[0m"
+if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
 fi
 
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
+
+if [[ "$2" == "--recreate-ca" ]]; then
+  create_ca "etcdCA" "$CA_NAME"
+  create_ca "peerCA" "$PEER_CA_NAME"
+else
+  if [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
+    create_ca "etcdCA" "$CA_NAME"
+  else
+    echo -e "\e[1m\e[33m[INFO] Using existing etcd CA, recreating only client/server certificates\e[0m"
+  fi
+  if [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$PEER_CA_NAME.crt" ]]; then
+    create_ca "peerCA" "$PEER_CA_NAME"
+  else
+    echo -e "\e[1m\e[33m[INFO] Using existing peer CA, recreating only client/server certificates\e[0m"
+  fi
+fi
+
+CC_CN="cf-etcd.service.cf.internal"
+DOMAIN="*.$CC_CN,$CC_CN"
 # Server certificate to share across the etcd cluster
-"${scripts_folder}"/generate_end_entity_certs --common-name "cf-etcd.service.cf.internal" --ca-name etcd-ca --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' --depot-path "${depot_path}" --output-file server
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "$CC_CN" --ca-name "$CA_NAME" --domain "$DOMAIN" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file server
 
 # Client certificate to distribute to jobs that access etcd
-"${scripts_folder}"/generate_end_entity_certs --common-name "clientName" --ca-name etcd-ca --depot-path "${depot_path}" --output-file client
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "clientName" --ca-name "$CA_NAME" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file client
 
 # Client certificate to distribute across etcd peers
-"${scripts_folder}"/generate_end_entity_certs --common-name cf-etcd.service.cf.internal --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' --ca-name peer-ca --depot-path "${depot_path}" --output-file peer
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "$CC_CN" --domain "$DOMAIN" --ca-name "$PEER_CA_NAME" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file peer
diff --git a/scripts/generate-loggregator-certs b/scripts/generate-loggregator-certs
--- a/scripts/generate-loggregator-certs
+++ b/scripts/generate-loggregator-certs
@@ -2,71 +2,63 @@
 
 set -e
 
-if [ "$1" = "" ]; then
-    echo "usage: $0 <cf-credentials-folder> [--recreate-ca]"
-    echo "       $0 no-bbs-ca [--recreate-ca]"
-    exit 1
-fi
+SCRIPTS_FOLDER="$(dirname "$0")"
 
-readlink() {
-  (
-    cd "$(dirname "$1")"
-    echo "$PWD/$(basename "$1")"
-  )
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="loggregator-certs"
+CA_NAME="loggregator-ca"
+BBS_CA_NAME="$CA_NAME"
+
+function create_ca {
+  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "loggregatorCA" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$CA_NAME"
 }
 
-# Place keys and certificates here
-depot_path=$(readlink ./loggregator-certs)
-mkdir -p "${depot_path}"
-ca_name="loggregator-ca"
-
-if [ "$1" == "no-bbs-ca" ]; then
-    bbs_ca_name="$ca_name"
-else
-    bbs_ca_cert_path="$(find "$1" -name 'cf-diego-ca.crt')"
-    bbs_ca_key_path="$(find "$1" -name 'cf-diego-ca.key')"
-    bbs_ca_name="cf-diego-ca"
-    if [[ ! -f "$bbs_ca_cert_path" || ! -f "$bbs_ca_key_path" ]]; then
-        echo -e "\e[1m\e[33m[ERROR] Please execute generate-cf-diego-certs before running this script.\e[0m"
-        exit 1
-    fi
-    ln -s "${bbs_ca_cert_path}" "${depot_path}"/
-    ln -s "${bbs_ca_key_path}" "${depot_path}"/
+if [[ "$1" == "--recreate-ca" || "$1" == "no-bbs-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
 fi
 
-if [[ "$2" == "--recreate-ca" ]] || [[ -z "$2" && ! -f "$depot_path/$ca_name.crt" ]]; then
-  # CA to distribute to loggregator certs
-  certstrap --depot-path "${depot_path}" init --passphrase '' --common-name loggregatorCA
-  mv -f "${depot_path}/loggregatorCA.crt" "${depot_path}/$ca_name.crt"
-  mv -f "${depot_path}/loggregatorCA.key" "${depot_path}/$ca_name.key"
-  mv -f "${depot_path}/loggregatorCA.crl" "${depot_path}/$ca_name.crl"
-elif [[ -z "$2" && -f "$depot_path/$ca_name.crt" ]]; then
-  echo -e "\e[1m\e[33m[INFO] Using existing loggregator CA, recreating only client/server certificates\e[0m"
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
+
+if [[ "$2" == "--recreate-ca" ]]; then
+  echo -e "\e[1m\e[33m[INFO] Recreating only the loggregatorCA. To recreate the diegoCA, please execute the script '$SCRIPTS_FOLDER/generate-cf-diego-certs'\e[0m"
+  create_ca
+elif [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
+  create_ca
 fi
-find "${depot_path}" -type f -not -name "$ca_name*" -delete
+
+if [[ -z "$3" || "$3" != "--no-bbs-ca" ]]; then
+  bbs_ca_cert_path="$(find "$ROOT_DEPOT_PATH" -name 'cf-diego-ca.crt')"
+  bbs_ca_key_path="$(find "$ROOT_DEPOT_PATH" -name 'cf-diego-ca.key')"
+  if [[ -z "$bbs_ca_cert_path" || -z "$bbs_ca_key_path" ]]; then
+    echo -e "\e[1m\e[33m[ERROR] Please execute '$SCRIPTS_FOLDER/generate-cf-diego-certs' before running this script.\e[0m"
+    exit 1
+  fi
+  bbs_ca_cert_path="$(realpath "$bbs_ca_cert_path")"
+  bbs_ca_key_path="$(realpath "$bbs_ca_key_path")"
+  BBS_CA_NAME="cf-diego-ca"
+  ln -s "$bbs_ca_cert_path" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
+  ln -s "$bbs_ca_key_path" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
+fi
+
+find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type f -not -name "$CA_NAME*" -not -name "cf-diego-ca*" -delete
 
 # Doppler certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name doppler
-certstrap --depot-path "${depot_path}" sign doppler --CA "$ca_name"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name doppler-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file doppler
 
 # Traffic Controller certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name trafficcontroller
-certstrap --depot-path "${depot_path}" sign trafficcontroller --CA "$ca_name"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name trafficcontroller-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file trafficcontroller
 
 # Traffic Controller<->CAPI mutual TLS certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name cc_trafficcontroller
-certstrap --depot-path "${depot_path}" sign cc_trafficcontroller --CA "${bbs_ca_name}"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name cc_trafficcontroller-cn --ca-name "$BBS_CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file cc_trafficcontroller
 
 # Metron certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name metron
-certstrap --depot-path "${depot_path}" sign metron --CA "$ca_name"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name metron-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file metron
 
 # Reverse Log Proxy certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name reverselogproxy
-certstrap --depot-path "${depot_path}" sign reverselogproxy --CA "$ca_name"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name reverselogproxy-cn --ca-name "$CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file reverselogproxy
 
 # Syslog drain binder certificate
-certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name syslogdrainbinder
-certstrap --depot-path "${depot_path}" sign syslogdrainbinder --CA "${bbs_ca_name}"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name syslogdrainbinder-cn --ca-name "$BBS_CA_NAME" --depot-path "$ROOT_DEPOT_PATH/$DEPOT_PATH" --output-file syslogdrainbinder
 
-rm -f "${depot_path}"/cf-diego-ca.{crt,key}
+find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type l -name "cf-diego-ca*" -delete
diff --git a/scripts/generate-statsd-injector-certs b/scripts/generate-statsd-injector-certs
--- a/scripts/generate-statsd-injector-certs
+++ b/scripts/generate-statsd-injector-certs
@@ -2,37 +2,32 @@
 
 set -e
 
-scripts_folder="$(dirname "$0")"
+SCRIPTS_FOLDER="$(dirname "$0")"
 
-if [ "$1" = "" ]; then
-    echo "usage: $0 <cf-credentials-folder> [--recreate-ca]"
-    exit 1
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="statsd-injector-certs"
+
+if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
 fi
 
-readlink() {
-  (
-    cd "$(dirname "$1")"
-    echo "$PWD/$(basename "$1")"
-  )
-}
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
 
-# Place keys and certificates here
-depot_path=$(readlink ./statsd-injector-certs)
-mkdir -p "${depot_path}"
-
-loggregator_ca_cert_path="$(find "$1/loggregator-certs" -name 'loggregator-ca.crt')"
-loggregator_ca_key_path="$(find "$1/loggregator-certs" -name 'loggregator-ca.key')"
-if [[ ! -f "$loggregator_ca_cert_path" || ! -f "$loggregator_ca_key_path" ]]; then
-    echo -e "\e[1m\e[33m[ERROR] Please execute generate-loggregator-certs before running this script.\e[0m"
-    exit 1
+LOGGREGATOR_CA_CERT_PATH="$(find "$ROOT_DEPOT_PATH" -name 'loggregator-ca.crt')"
+LOGGREGATOR_CA_KEY_PATH="$(find "$ROOT_DEPOT_PATH" -name 'loggregator-ca.key')"
+if [[ -z "$LOGGREGATOR_CA_CERT_PATH" || -z "$LOGGREGATOR_CA_KEY_PATH" ]]; then
+  echo -e "\e[1m\e[33m[ERROR] Please execute '$SCRIPTS_FOLDER/generate-loggregator-cert' before running this script.\e[0m"
+  exit 1
 fi
 
-find "$depot_path" -type l -delete
-ln -s "${loggregator_ca_cert_path}" "${depot_path}/"
-ln -s "${loggregator_ca_key_path}" "${depot_path}/"
+LOGGREGATOR_CA_CERT_PATH="$(realpath "$LOGGREGATOR_CA_CERT_PATH")"
+LOGGREGATOR_CA_KEY_PATH="$(realpath "$LOGGREGATOR_CA_KEY_PATH")"
+ln -s "${LOGGREGATOR_CA_CERT_PATH}" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
+ln -s "${LOGGREGATOR_CA_KEY_PATH}" "${ROOT_DEPOT_PATH}/${DEPOT_PATH}/"
 
 # Statsd injector certificate
 server_cn="statsdinjector.service.cf.internal"
-"${scripts_folder}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name loggregator-ca --depot-path "${depot_path}" --output-file statsdinjector
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name loggregator-ca --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file statsdinjector
 
-find "$depot_path" -type l -delete
+find "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" -type l -delete
diff --git a/scripts/generate-uaa-certs b/scripts/generate-uaa-certs
--- a/scripts/generate-uaa-certs
+++ b/scripts/generate-uaa-certs
@@ -2,20 +2,29 @@
 
 set -e
 
-scripts_folder="$(dirname "$0")"
+SCRIPTS_FOLDER="$(dirname "$0")"
 
-# Place keys and certificates here
-depot_path="uaa-certs"
-mkdir -p "${depot_path}"
-ca_name="uaa-ca"
+ROOT_DEPOT_PATH="$1"
+DEPOT_PATH="uaa-certs"
+CA_NAME="uaa-ca"
 
-if [[ "$1" == "--recreate-ca" ]] || [[ -z "$1" && ! -f "$depot_path/$ca_name.crt" ]]; then
-  # CA to generate client certs
-  "${scripts_folder}"/generate_ca_cert --common-name "cert-authority" --depot-path "${depot_path}" --output-file "$ca_name"
-elif [[ -z "$1" && -f "$depot_path/$ca_name.crt" ]]; then
+function create_ca {
+  "${SCRIPTS_FOLDER}"/generate_ca_cert --common-name "uaaCA" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file "$CA_NAME"
+}
+
+if [[ "$1" == "--recreate-ca" || -z "$1" || ! -d "$1" ]]; then
+  echo -e "\e[1m\e[31m[ERROR] Missing ROOT_DEPOT_PATH parameter.\e[0m"
+  exit 1
+fi
+
+test -d "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" || mkdir -p "${ROOT_DEPOT_PATH}/${DEPOT_PATH}"
+
+if [[ "$2" == "--recreate-ca" ]] || [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && ! -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
+  create_ca
+elif [[ -d "$ROOT_DEPOT_PATH/$DEPOT_PATH" && -f "$ROOT_DEPOT_PATH/$DEPOT_PATH/$CA_NAME.crt" ]]; then
   echo -e "\e[1m\e[33m[INFO] Using existing uaa CA, recreating only client/server certificates\e[0m"
 fi
 
 # Certificate to use as the client
-server_cn="uaa.service.cf.internal"
-"${scripts_folder}"/generate_end_entity_certs --common-name "${server_cn}" --ca-name "$ca_name" --depot-path "${depot_path}" --output-file server
+SERVER_CN="uaa.service.cf.internal"
+"${SCRIPTS_FOLDER}"/generate_end_entity_certs --common-name "$SERVER_CN" --ca-name "$CA_NAME" --depot-path "${ROOT_DEPOT_PATH}/${DEPOT_PATH}" --output-file server
