Change for switching between NFSv3 and NFSv4 on cloud_controller
Change-Id: I988c33d2e2904ad70c74030c9b2567d70daee59c

diff --git a/jobs/cloud_controller/templates/cloud_controller_ctl.erb b/jobs/cloud_controller/templates/cloud_controller_ctl.erb
--- a/jobs/cloud_controller/templates/cloud_controller_ctl.erb
+++ b/jobs/cloud_controller/templates/cloud_controller_ctl.erb
@@ -70,14 +70,19 @@ case $1 in
     /etc/init.d/idmapd restart
 
     if grep -qs $NFS_SHARE /proc/mounts; then
-      echo "Found NFS mount"
-    else
-      echo "Mounting NFS..."
-      mount -o timeo=10,intr,lookupcache=positive -t nfs4 <%= properties.nfs_server.address %>:<%= properties.nfs_server.share || "/" %> $NFS_SHARE
-      if [ $? != 0 ]; then
-        echo "Cannot mount NFS, exiting..."
-        exit 1
-      fi
+      echo "Found NFS mount, unmounting..."
+      unmount $NFS_SHARE
+    fi
+
+    echo "Mounting NFS..."
+    <%- if properties.nfs_server.nfsv4 -%>
+    mount -o timeo=10,intr,lookupcache=positive -t nfs4 <%= properties.nfs_server.address %>:<%= properties.nfs_server.share || "/" %> $NFS_SHARE
+    <%- else -%>
+    mount -o timeo=10,intr,lookupcache=positive -t nfs <%= properties.nfs_server.address %>:<%= properties.nfs_server.share || "/var/vcap/store/shared" %> $NFS_SHARE
+    <%- end -%>
+    if [ $? != 0 ]; then
+      echo "Cannot mount NFS, exiting..."
+      exit 1
     fi
 
     chpst -u vcap:vcap touch $NFS_SHARE/.nfs_test
