add multi versions support for postgresql_node_ng
new postgresql91 package
support for both 9.0 and 9.1

$git shortlog e163e148..182a0f29
Andrew Liu (1):
      multi versions support for postgresql

Change-Id: Iddf9e55717cb953762b5fc60405cf87b0b9ee853

diff --git a/jobs/postgresql_node_ng/templates/warden_ctl b/jobs/postgresql_node_ng/templates/warden_ctl
--- a/jobs/postgresql_node_ng/templates/warden_ctl
+++ b/jobs/postgresql_node_ng/templates/warden_ctl
@@ -27,30 +27,43 @@ case $1 in
     sysctl -w 'kernel.shmall=<%=plan_conf.shmall%>'
     <%end%>
 
-    install -m 0755 -d $ROOT_DIR/$PG_DIR
-    rsync -arl $JOB_DIR/packages/postgresql/* $ROOT_DIR/$PG_DIR/
-    # create a initialized data dir
-    rm -rf $ROOT_DIR/$PG_DIR/initdb
-    mkdir -p /var/vcap/data/initdb_tmp
-    chmod -R 1777 /var/vcap/data/initdb_tmp
-    if test ! -d /var/vcap/data/initdb_tmp/initdb/base
-    then
-      rm -rf /var/vcap/data/initdb_tmp/initdb
-      echo "Initialize the postgresql database cluster."
-      su - vcap -c "LD_LIBRARY_PATH=$ROOT_DIR/$PG_DIR/lib:$LD_LIBRARY_PATH $ROOT_DIR/$PG_DIR/bin/initdb -E utf8 -D /var/vcap/data/initdb_tmp/initdb"
-    fi
-    if test ! -d /var/vcap/data/initdb_tmp/initdb/base
-    then
-      echo "Fail to initialize the postgresql database cluster, check the error log."
-      exit 1
-    fi
-    rsync -arl /var/vcap/data/initdb_tmp/initdb $ROOT_DIR/$PG_DIR
-    mkdir -p $ROOT_DIR/$PG_DIR/initdb/pg_log
-    chmod -R 777 $ROOT_DIR/$PG_DIR/initdb
-    install -m 0755 -t $ROOT_DIR/usr/sbin $JOB_DIR/bin/pre_service_start.sh
-    rsync -arl $JOB_DIR/bin/warden_service_ctl $ROOT_DIR/usr/bin/warden_service_ctl
-    chmod 0755 $ROOT_DIR/usr/bin/warden_service_ctl
+    for version in "9.0" "9.1"
+    do
+      case "$version" in
+        "9.0")
+          PG_DIR=/var/vcap/packages/postgresql
+          TMPDB_DIR=/var/vcap/data/initdb_tmp
+          ;;
+        "9.1")
+          PG_DIR=/var/vcap/packages/postgresql91
+          TMPDB_DIR=/var/vcap/data/initdb91_tmp
+          ;;
+      esac
 
+      echo "Initialize the postgresql $version database cluster"
+      install -m 0755 -d $ROOT_DIR/$PG_DIR
+      rsync -arl $PG_DIR/* $ROOT_DIR/$PG_DIR/
+
+      rm -rf $ROOT_DIR/$PG_DIR/initdb
+      mkdir -p $TMPDB_DIR
+      chmod -R 1777 $TMPDB_DIR
+      if test ! -d $TMPDB_DIR/initdb/base
+      then
+        rm -rf $TEMPDB_DIR/initdb
+        su - vcap -c "LD_LIBRARY_PATH=$ROOT_DIR/$PG_DIR/lib:$LD_LIBRARY_PATH $ROOT_DIR/$PG_DIR/bin/initdb -E utf8 -D $TMPDB_DIR/initdb"
+      fi
+      if test ! -d $TMPDB_DIR/initdb/base
+      then
+        echo "Fail to initialize the postgresql $version database cluster, check the error log."
+        exit 1
+      fi
+      rsync -arl $TMPDB_DIR/initdb $ROOT_DIR/$PG_DIR
+      mkdir -p $ROOT_DIR/$PG_DIR/initdb/pg_log
+      chmod -R 777 $ROOT_DIR/$PG_DIR/initdb
+      install -m 0755 -t $ROOT_DIR/usr/sbin $JOB_DIR/bin/pre_service_start.sh
+      rsync -arl $JOB_DIR/bin/warden_service_ctl $ROOT_DIR/usr/bin/warden_service_ctl
+      chmod 0755 $ROOT_DIR/usr/bin/warden_service_ctl
+    done
     echo "Starting warden."
 
     start_warden
